apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
data:
  # For git-sync v3
  GIT_SYNC_USERNAME: <USER IN BASE64>
  GIT_SYNC_PASSWORD: <TOKEN IN BASE64>
  # For git-sync v4
  GITSYNC_USERNAME: <USER IN BASE64>
  GITSYNC_PASSWORD: <TOKEN IN BASE64>
