apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-atlas
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-atlas
  template:
    metadata:
      labels:
        app: apache-atlas
    spec:
      containers:
        - name: apache-atlas
          image: sburn/apache-atlas
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 21000
          resources:
            requests:
              cpu: "4"
              memory: "4Gi"
            limits:
              cpu: "8"
              memory: "8Gi"
          readinessProbe:
            httpGet:
              path: /
              port: 21000
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 21000
            initialDelaySeconds: 120
            periodSeconds: 30
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: apache-atlas
  namespace: atlas
spec:
  type: NodePort
  selector:
    app: apache-atlas
  ports:
    - name: http
      port: 21000
      targetPort: 21000
      nodePort: 32100

