apiVersion: v1
kind: Namespace
metadata:
  name: bigdata-lab
---
# ============================
# ZOOKEEPER
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: bigdata-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: bigdata-lab
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
# ============================
# KAFKA
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: bigdata-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CREATE_TOPICS
              value: "create_events:1:1,delete_events:1:1,ATLAS_HOOK:1:1"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: bigdata-lab
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
---
# ============================
# ATLAS
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-server
  namespace: bigdata-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-server
  template:
    metadata:
      labels:
        app: atlas-server
    spec:
      containers:
        - name: atlas-server
          image: lucasmsp/atlas:2.3
          ports:
            - containerPort: 21000
          volumeMounts:
            - name: atlas-models
              mountPath: /opt/atlas/models/1000-Hadoop
          env:
            - name: ZOOKEEPER_HOST
              value: zookeeper
            - name: KAFKA_HOST
              value: kafka
      volumes:
        - name: atlas-models
          hostPath:
            path: ./atlas/resources/1000-Hadoop
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-server
  namespace: bigdata-lab
spec:
  selector:
    app: atl
