apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-server
  template:
    metadata:
      labels:
        app: atlas-server
    spec:
      containers:
        - name: atlas-server
          image: lucasmsp/atlas:2.3
          ports:
            - containerPort: 21000
          volumeMounts:
            - name: atlas-models
              mountPath: /opt/atlas/models/1000-Hadoop
          env:
            - name: ZOOKEEPER_HOST
              value: zookeeper
            - name: KAFKA_HOST
              value: kafka
      volumes:
        - name: atlas-models
          hostPath:
            path: ./atlas/resources/1000-Hadoop
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-server
spec:
  selector:
    app: atlas-server
  ports:
    - port: 21000
      targetPort: 21000
